# Generated by Django 2.0.3 on 2018-08-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('number', models.CharField(max_length=32, verbose_name='手机号')),
                ('device_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备id')),
                ('sort', models.CharField(max_length=64, verbose_name='类别')),
                ('content', models.CharField(max_length=10240, verbose_name='内容')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
            },
        ),
    ]
