# Generated by Django 2.0.3 on 2018-09-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuPei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('number', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号')),
                ('user_id', models.IntegerField(unique=True, verbose_name='用户id')),
                ('send_count', models.IntegerField(default=0, verbose_name='申请次数')),
                ('amount', models.IntegerField(default=0, help_text='单位：分', verbose_name='可赔付金额')),
                ('withdraw', models.IntegerField(default=0, verbose_name='已提现金额')),
            ],
            options={
                'verbose_name': '拒就赔',
                'verbose_name_plural': '拒就赔',
            },
        ),
    ]
