"""
Django settings for daoliu project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'NO').lower() in ('on', 'true', 'y', 'yes')
PRODUCTION = os.getenv('PRODUCTION', 'NO').lower() in ('on', 'true', 'y', 'yes')

CDN_BASE = os.environ['CDN_BASE']
JIE_DOMAIN = os.getenv('JIE_DOMAIN', 'https://api.jieqiankuaishou.com')
API_ID_INFO = os.environ['API_ID_INFO']
API_PHONE_INFO = os.environ['API_PHONE_INFO']
API_BASE_USER = os.environ['API_BASE_USER']
INTENAL_BASE = os.getenv('INTENAL_BASE', '')
API_MOBILE_HIT = os.environ['API_MOBILE_HIT']
MONGO_DB_JIEAPI = os.environ['MONGO_DB_JIEAPI']

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rangefilter',
    'common',
    'profiles',
    'stores',
    'api_infos',
    'topics',
    'collects',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'common.middleware.jwt_token_middleware',
    'common.middleware.user_agent_middleware',
]


ROOT_URLCONF = 'general.urls'

WSGI_APPLICATION = 'general.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ['DB_NAME'],
        'OPTIONS': {'charset': 'utf8mb4'},
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASS'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
        'TEST': {
            'CHARSET': 'utf8mb4',
        },
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

TIME_ZONE = 'Asia/Shanghai'
LANGUAGE_CODE = 'zh-hans'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = CDN_BASE + '/s/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

if DEBUG:
    INSTALLED_APPS += ('debug_toolbar',)
    MIDDLEWARE += ('debug_toolbar.middleware.DebugToolbarMiddleware', )
    INTERNAL_IPS = ['127.0.0.1']

    def show_toolbar(request):
        return True

    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": show_toolbar,
    }


# rest_framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (),
    'DATETIME_FORMAT': '%Y/%m/%d %H:%M:%S',
    'DATETIME_INPUT_FORMATS': ['%Y/%m/%d %H:%M:%S', 'iso-8601'],
}

# media
STATIC_URL = CDN_BASE + '/s/'
MEDIA_URL = os.environ['MEDIA_BASE'] + "/"
DEFAULT_FILE_STORAGE = 'aliyun_oss.backends.oss.OSSStorage'

OSS_ACCESS_KEY_ID = os.environ['OSS_ACCESS_KEY_ID']
OSS_SECRET_ACCESS_KEY = os.environ['OSS_SECRET_ACCESS_KEY']
OSS_ACCESS_URL = os.environ['OSS_ACCESS_URL']
OSS_STORAGE_BUCKET_NAME = os.environ['OSS_STORAGE_BUCKET_NAME']


ADMINS = [('id', 'id@huohuod.com')]
EMAIL_BACKEND = 'general.email.EmailBackend'

# redis
REDIS_HOST = os.environ['REDIS_HOST']
REDIS_PWD = os.environ.get('REDIS_PWD')
REDIS_DB = os.environ.get('REDIS_DB')


CACHES = {
    'default': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': [
            "%s:6379" % REDIS_HOST,
        ],
        'TIMEOUT': None,
        'OPTIONS': {
            'DB': REDIS_DB,
            'PASSWORD': REDIS_PWD,
            'PARSER_CLASS': 'redis.connection.HiredisParser',
            'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool',
            'CONNECTION_POOL_CLASS_KWARGS': {
                'max_connections': 50,
                'timeout': 20,
            },
            'MAX_CONNECTIONS': 1000,
            'PICKLE_VERSION': -1,
        },
    },
}

# mongo
MONGO_SERVER = os.environ['MONGO_SERVER']
MONGO_DB = os.environ['MONGO_DB']

# set session nearly never expire
SESSION_COOKIE_AGE = 86400*1000

VERSION = '201803301151'
