# Generated by Django 2.0.3 on 2018-07-18 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.IntegerField(db_index=True, verbose_name='用户id')),
                ('content', models.TextField(verbose_name='内容')),
                ('status', models.SmallIntegerField(choices=[(0, '审核中'), ('1', '审核拒绝'), (2, '审核通过')], default=2, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.IntegerField(db_index=True, verbose_name='用户id')),
                ('content', models.TextField(verbose_name='内容')),
                ('status', models.SmallIntegerField(choices=[(0, '审核中'), ('1', '审核拒绝'), (2, '审核通过')], default=2, verbose_name='审核状态')),
                ('comment_type', models.SmallIntegerField(choices=[(0, '评论一个主题'), (1, '评论一条评论')], default=0, verbose_name='评论类型')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_comments', to='topics.Article', verbose_name='主题id')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_comments', to='topics.Comment', verbose_name='父级评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created'],
            },
        ),
    ]
