# Generated by Django 2.0.3 on 2018-07-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20180730_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='review_msg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='审核意见'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '审核中'), ('1', '审核拒绝'), (2, '审核通过'), (3, '人工审核')], default=0, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '审核中'), ('1', '审核拒绝'), (2, '审核通过'), (3, '人工审核')], default=2, verbose_name='审核状态'),
        ),
    ]
