# Generated by Django 2.0.3 on 2018-07-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20180730_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '审核中'), ('1', '审核拒绝'), (2, '审核通过'), (3, '人工审核')], default=0, verbose_name='审核状态'),
        ),
    ]
