# Generated by Django 2.0.3 on 2018-08-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20180730_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '审核中'), (1, '审核拒绝'), (2, '审核通过'), (3, '人工审核')], default=0, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '审核中'), (1, '审核拒绝'), (2, '审核通过'), (3, '人工审核')], default=0, verbose_name='审核状态'),
        ),
    ]
