# Generated by Django 2.0.3 on 2018-08-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20180801_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='不可以更改', max_length=16, verbose_name='标记')),
                ('desc', models.CharField(max_length=64, verbose_name='描述')),
                ('article_gap', models.PositiveIntegerField(help_text='单位:秒', verbose_name='发帖间隔时间')),
                ('article_same', models.PositiveIntegerField(help_text='单位:秒', verbose_name='发重复内容间隔时间')),
            ],
            options={
                'verbose_name': '审核配置',
                'verbose_name_plural': '审核配置',
            },
        ),
    ]
