# Generated by Django 2.0.3 on 2018-08-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_timeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeconfig',
            name='article_same_rate',
            field=models.SmallIntegerField(blank=True, help_text='百分比：90', null=True, verbose_name='内容相似度'),
        ),
    ]
