# Generated by Django 2.0.3 on 2018-08-13 06:20

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_timeconfig_article_same_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='标记')),
                ('black_user', jsonfield.fields.JSONField(blank=True, default=[], null=True, verbose_name='用户id黑名单')),
                ('black_msg', models.CharField(blank=True, max_length=64, null=True, verbose_name='原因')),
            ],
            options={
                'verbose_name': '审核黑名单',
                'verbose_name_plural': '审核黑名单',
            },
        ),
    ]
