# Generated by Django 2.0.3 on 2018-08-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_reviewblacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='art_type',
            field=models.SmallIntegerField(choices=[(0, ''), (1, '出借'), (2, '求借')], default=0, verbose_name='出/求借'),
        ),
        migrations.AddField(
            model_name='article',
            name='loan_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='借款金额'),
        ),
        migrations.AddField(
            model_name='article',
            name='loan_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='article',
            name='loan_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='借款期限'),
        ),
    ]
