# Generated by Django 2.0.3 on 2018-08-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_auto_20180815_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户手机号'),
        ),
        migrations.AddField(
            model_name='comment',
            name='number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户手机号'),
        ),
        migrations.AddField(
            model_name='timeconfig',
            name='is_push',
            field=models.BooleanField(default=True, verbose_name='是否推送'),
        ),
    ]
