# Generated by Django 2.0.3 on 2018-08-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0011_auto_20180816_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='不可以更改', max_length=16, unique=True, verbose_name='标记')),
                ('is_push', models.BooleanField(default=True, verbose_name='是否推送')),
                ('content', models.CharField(max_length=128, verbose_name='推送内容')),
            ],
            options={
                'verbose_name': '推送配置',
                'verbose_name_plural': '推送配置',
            },
        ),
        migrations.RemoveField(
            model_name='timeconfig',
            name='is_push',
        ),
        migrations.AlterField(
            model_name='article',
            name='art_type',
            field=models.SmallIntegerField(choices=[(0, ''), (1, '出借'), (2, '求借')], db_index=True, default=0, verbose_name='出/求借'),
        ),
    ]
