# Generated by Django 2.0.3 on 2018-07-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('number', models.CharField(max_length=15, verbose_name='手机号')),
                ('identification', models.CharField(max_length=22, verbose_name='身份证号')),
                ('ip', models.CharField(max_length=32, verbose_name='ip 地址')),
            ],
            options={
                'verbose_name': '保险信息',
                'verbose_name_plural': '保险信息',
            },
        ),
    ]
