# Generated by Django 2.0.3 on 2018-07-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_infos', '0003_auto_20180703_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceinfomodel',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='生日'),
        ),
    ]
