# Generated by Django 2.0.3 on 2018-07-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_infos', '0004_insuranceinfomodel_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True, verbose_name='手机号')),
                ('amount', models.IntegerField(verbose_name='万元')),
                ('period', models.IntegerField(verbose_name='月')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('identification', models.CharField(max_length=22, verbose_name='身份证号')),
                ('province', models.CharField(max_length=16, verbose_name='省份')),
                ('city', models.CharField(max_length=16, verbose_name='城市')),
                ('marriage', models.CharField(max_length=12, verbose_name='婚姻状况')),
                ('local_account', models.CharField(max_length=4, verbose_name='是否本地户口')),
                ('credit_choice', models.CharField(max_length=8, verbose_name='是否本地户口')),
                ('job', models.CharField(max_length=8, verbose_name='是否本地户口')),
                ('company', models.CharField(max_length=64, verbose_name='是否本地户口')),
                ('income_bank', models.IntegerField(blank=True, null=True, verbose_name='月收入（银行代发工资）')),
                ('income_month', models.IntegerField(blank=True, null=True, verbose_name='月收入（现金）')),
                ('job_age', models.IntegerField(verbose_name='工龄')),
                ('local_social_security', models.CharField(max_length=64, verbose_name='是否有本地社保')),
                ('local_fund', models.CharField(max_length=64, verbose_name='是否有本地公积金')),
                ('amount_weilidai', models.IntegerField(verbose_name='微粒贷额度（元）')),
                ('amount_mayijiebei', models.IntegerField(verbose_name='蚂蚁借呗额度（元）')),
                ('has_house', models.CharField(max_length=64, verbose_name='有房产')),
                ('has_insurance', models.CharField(max_length=64, verbose_name='有保险')),
                ('has_car', models.CharField(max_length=64, verbose_name='有汽车')),
                ('birthday', models.DateTimeField(null=True, verbose_name='生日')),
                ('ip', models.CharField(max_length=32, verbose_name='ip 地址')),
                ('c001_status', models.SmallIntegerField(choices=[(0, '未发送'), (1, '发送中'), (2, '发送失败'), (3, '发送成功')], default=0, verbose_name='黑牛贷款')),
                ('c002_status', models.SmallIntegerField(choices=[(0, '未发送'), (1, '发送中'), (2, '发送失败'), (3, '发送成功')], default=0, verbose_name='助贷网')),
            ],
            options={
                'verbose_name': '收集信息',
                'verbose_name_plural': '收集信息',
            },
        ),
        migrations.AlterField(
            model_name='insuranceinfomodel',
            name='number',
            field=models.CharField(max_length=15, unique=True, verbose_name='手机号'),
        ),
    ]
