# Generated by Django 2.0.3 on 2018-07-03 09:55

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api_infos', '0005_auto_20180703_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsmodel',
            name='identification',
            field=models.CharField(max_length=22, validators=[utils.validators.id_validator], verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='insuranceinfomodel',
            name='identification',
            field=models.CharField(max_length=22, validators=[utils.validators.id_validator], verbose_name='身份证号'),
        ),
    ]
