# Generated by Django 2.0.3 on 2018-07-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_infos', '0006_auto_20180703_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsmodel',
            name='number',
            field=models.CharField(max_length=15, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='insuranceinfomodel',
            name='number',
            field=models.CharField(max_length=15, verbose_name='手机号'),
        ),
    ]
