# Generated by Django 2.0.3 on 2018-07-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_infos', '0007_auto_20180703_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionsModel',
        ),
    ]
