# Generated by Django 2.0.3 on 2018-09-19 03:24

from django.db import migrations, models
import django.utils.timezone
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('number', models.CharField(max_length=15, unique=True, verbose_name='手机号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('identification', models.CharField(blank=True, max_length=22, null=True, validators=[utils.validators.id_validator], verbose_name='身份证号')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='万元')),
                ('period', models.IntegerField(blank=True, null=True, verbose_name='月')),
                ('province', models.CharField(blank=True, max_length=16, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=16, null=True, verbose_name='城市')),
                ('marriage', models.CharField(blank=True, max_length=12, null=True, verbose_name='婚姻状况')),
                ('local_account', models.CharField(blank=True, max_length=4, null=True, verbose_name='是否本地户口')),
                ('credit_choice', models.CharField(blank=True, max_length=8, null=True, verbose_name='是否有信用卡')),
                ('job', models.CharField(blank=True, max_length=8, null=True, verbose_name='工作')),
                ('company', models.CharField(blank=True, max_length=64, null=True, verbose_name='公司')),
                ('income_bank', models.IntegerField(default=0, verbose_name='月收入（银行代发工资）')),
                ('income_month', models.IntegerField(default=0, verbose_name='月收入（现金）')),
                ('job_age', models.IntegerField(blank=True, null=True, verbose_name='工龄')),
                ('local_social_security', models.CharField(blank=True, max_length=64, null=True, verbose_name='是否有本地社保')),
                ('local_fund', models.CharField(blank=True, max_length=64, null=True, verbose_name='是否有本地公积金')),
                ('has_house', models.CharField(blank=True, max_length=64, null=True, verbose_name='有房产')),
                ('has_insurance', models.CharField(blank=True, max_length=64, null=True, verbose_name='有保险')),
                ('has_car', models.CharField(blank=True, max_length=64, null=True, verbose_name='有汽车')),
                ('has_creditcard', models.CharField(blank=True, max_length=64, null=True, verbose_name='有信用卡')),
                ('has_car_loan', models.CharField(blank=True, max_length=64, null=True, verbose_name='有车贷')),
                ('has_house_loan', models.CharField(blank=True, max_length=64, null=True, verbose_name='有房贷')),
                ('amount_creditcard', models.IntegerField(blank=True, null=True, verbose_name='信用卡额度（元）')),
                ('amount_weilidai', models.IntegerField(blank=True, null=True, verbose_name='微粒贷额度（元）')),
                ('amount_mayijiebei', models.IntegerField(blank=True, null=True, verbose_name='蚂蚁借呗额度（元）')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='生日')),
                ('birth', models.CharField(blank=True, max_length=32, null=True, verbose_name='手填生日')),
                ('sex', models.CharField(blank=True, max_length=32, null=True, verbose_name='性别')),
                ('way', models.CharField(blank=True, max_length=4, null=True, verbose_name='上班族_工资发放')),
                ('license', models.CharField(blank=True, max_length=4, null=True, verbose_name='私营业主_营业执照')),
                ('seniority', models.CharField(blank=True, max_length=4, null=True, verbose_name='黑牛工龄')),
                ('salary', models.CharField(blank=True, max_length=4, null=True, verbose_name='月薪')),
                ('ip', models.CharField(max_length=32, verbose_name='ip 地址')),
                ('c001_status', models.SmallIntegerField(choices=[(0, '未发送'), (1, '发送中'), (2, '发送失败'), (3, '发送成功')], default=0, verbose_name='黑牛贷款')),
                ('c002_status', models.SmallIntegerField(choices=[(0, '未发送'), (1, '发送中'), (2, '发送失败'), (3, '发送成功')], default=0, verbose_name='助贷网')),
                ('c003_status', models.SmallIntegerField(choices=[(0, '未发送'), (1, '发送中'), (2, '发送失败'), (3, '发送成功')], default=0, verbose_name='东方融资网')),
            ],
            options={
                'verbose_name': '收集信息',
                'verbose_name_plural': '收集信息',
            },
        ),
    ]
