# Generated by Django 2.0.3 on 2018-09-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsmodel',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='浏览器信息'),
        ),
    ]
