# Generated by Django 2.0.3 on 2018-09-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0002_collectionsmodel_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsmodel',
            name='c004_status',
            field=models.SmallIntegerField(choices=[(0, '未发送'), (1, '发送中'), (2, '发送失败'), (3, '发送成功')], default=0, verbose_name='龙分期'),
        ),
    ]
