# Generated by Django 2.0.3 on 2018-06-25 05:54

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='stores/activity', verbose_name='活动图片')),
                ('rank', models.PositiveIntegerField(default=0, help_text='数值越大越靠前', verbose_name='排序')),
            ],
            options={
                'verbose_name': '首页-活动',
                'verbose_name_plural': '首页-活动',
                'ordering': ['-rank'],
            },
        ),
        migrations.CreateModel(
            name='CouponBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('image', models.ImageField(upload_to='stores/banner', verbose_name='图片')),
                ('desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('rank', models.PositiveIntegerField(default=0, help_text='数值越大越靠前', verbose_name='排序')),
                ('banner_UI', jsonfield.fields.JSONField(help_text='{"up": 16}等', null=True, verbose_name='横幅配置')),
            ],
            options={
                'verbose_name': '信用币首页-横幅',
                'verbose_name_plural': '信用币首页-横幅',
                'ordering': ['-rank'],
            },
        ),
        migrations.CreateModel(
            name='CouponNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('detail', models.CharField(help_text='小***明 兑换了10元话费', max_length=128, verbose_name='消息')),
            ],
            options={
                'verbose_name': '大家在换-头条',
                'verbose_name_plural': '大家在换-头条',
            },
        ),
        migrations.CreateModel(
            name='CouponType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='名称')),
                ('sub_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='副标题(选填)')),
                ('desc', models.CharField(max_length=64, verbose_name='备注')),
                ('icon', models.ImageField(upload_to='stores/icon', verbose_name='图标')),
                ('json_detail', jsonfield.fields.JSONField(help_text='["介绍2", "介绍1"]', null=True, verbose_name='权益介绍')),
                ('json_usage', jsonfield.fields.JSONField(help_text='["使用 a", "使用 b"]', null=True, verbose_name='使用方法')),
                ('is_phone', models.BooleanField(default=False, verbose_name='是否话费充值')),
                ('is_phone_flow', models.BooleanField(default=False, verbose_name='是否手机流量充值')),
                ('phone_amount', models.PositiveIntegerField(blank=True, help_text='单位：分，10元填1000，充流量时只支持：1000，3000，5000', null=True, verbose_name='话费/流量金额')),
                ('is_credit_coin', models.BooleanField(default=False, verbose_name='是否是奖励信用币')),
                ('credit_coin_amount', models.PositiveIntegerField(blank=True, help_text='单位：个', null=True, verbose_name='奖励信用币')),
                ('rank', models.PositiveIntegerField(db_index=True, default=0, help_text='数值越大越靠前', verbose_name='排序')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热门')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否生效')),
                ('section', models.CharField(choices=[('C', '信用权益'), ('loan', '借款券')], default='credit', max_length=16, verbose_name='券类型')),
                ('only_once_year', models.BooleanField(default=False, help_text='对生日礼包，节日礼包等，要限制为1次，一年一次', verbose_name='一年只能领取一次')),
                ('only_once_ever', models.BooleanField(default=False, help_text='对新人礼包等，要限制为1次，从此不能再领', verbose_name='一人只能领取一次')),
                ('credit_coin', models.PositiveIntegerField(default=0, verbose_name='消耗信用币数量')),
                ('level_min', models.CharField(blank=True, help_text='例如 B（做过身份证和手机号认证），不填表示对信用等级没有要求', max_length=4, null=True, verbose_name='信用等级要求')),
                ('start_time', models.DateTimeField(blank=True, help_text='可选', null=True, verbose_name='开始日期')),
                ('end_time', models.DateTimeField(blank=True, help_text='可选', null=True, verbose_name='结束日期')),
                ('effective_days', models.IntegerField(blank=True, null=True, verbose_name='有效天数')),
                ('is_new_register', models.BooleanField(default=False, help_text='注册7天内', verbose_name='新人专享')),
                ('is_birthday', models.BooleanField(default=False, help_text='只在生日当天可以使用，一年最多领一次', verbose_name='生日专享')),
            ],
            options={
                'verbose_name': '优惠券类型',
                'verbose_name_plural': '优惠券类型',
                'ordering': ['-rank'],
            },
        ),
        migrations.CreateModel(
            name='CreditCoinConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='名称')),
                ('uid', models.CharField(default='', max_length=24, unique=True, verbose_name='字段标记')),
                ('desc', models.CharField(max_length=64, verbose_name='描述')),
                ('icon', models.ImageField(upload_to='stores/icon', verbose_name='图标')),
                ('credit_coin_amount', models.PositiveIntegerField(default=0, help_text='单位：个', verbose_name='奖励信用币')),
                ('is_continue', models.BooleanField(default=False, help_text='例如邀请好友任务，每天可以做多次', verbose_name='可重复任务')),
                ('rank', models.PositiveIntegerField(db_index=True, default=0, help_text='数值越大越靠前', verbose_name='排序')),
                ('json_event', jsonfield.fields.JSONField(blank=True, help_text='格式:{}，约定跳转到原生页面', null=True, verbose_name='跳转')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否生效')),
            ],
            options={
                'verbose_name': '赚信用币',
                'verbose_name_plural': '赚信用币',
                'ordering': ['-rank'],
            },
        ),
        migrations.AddField(
            model_name='couponnews',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.CouponType', verbose_name='选择券'),
        ),
        migrations.AddField(
            model_name='couponbanner',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.CouponType', verbose_name='选择券'),
        ),
        migrations.AddField(
            model_name='couponactivity',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.CouponType', verbose_name='选择券'),
        ),
    ]
